import { useState } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { GroupStackParamList } from '../navigation/types';
import { createGroup } from '../features/groups/api';
import { PageTitle, PrimaryButton, Screen, SectionLabel } from '../ui/Primitives';
import { useAppTheme, typography } from '../ui/theme';

type Props = NativeStackScreenProps<GroupStackParamList, 'CreateGroup'>;
export function CreateGroupScreen({ navigation }: Props) { const theme = useAppTheme(); const client = useQueryClient(); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [currency, setCurrency] = useState('IDR'); const [error, setError] = useState(''); const mutation = useMutation({ mutationFn: createGroup, onSuccess: async (groupId) => { await client.invalidateQueries({ queryKey: ['groups'] }); navigation.replace('GroupDetail', { groupId }); }, onError: (err) => setError(err.message) }); return <Screen scroll contentStyle={styles.container}><PageTitle subtitle="A clean place for every shared cost.">Create a group</PageTitle><SectionLabel>GROUP IDENTITY</SectionLabel><Field label="Group name" value={name} onChangeText={setName} placeholder="Trip Bali 2026" theme={theme} /><Field label="Description" value={description} onChangeText={setDescription} placeholder="Weekend expenses" theme={theme} /><Field label="Default currency" value={currency} onChangeText={(value) => setCurrency(value.toUpperCase())} placeholder="IDR" maxLength={3} autoCapitalize="characters" theme={theme} /><Text style={[typography.body, { color: theme.colors.inkMuted, marginTop: -2 }]}>All expenses in this group use the same currency.</Text>{!!error && <Text style={[typography.body, { color: theme.colors.error, marginTop: 14 }]}>{error}</Text>}<View style={styles.action}><PrimaryButton disabled={mutation.isPending} onPress={() => { if (!name.trim()) return setError('Group name is required.'); if (!/^[A-Z]{3}$/.test(currency)) return setError('Currency must be a 3-letter code.'); setError(''); mutation.mutate({ name: name.trim(), description: description.trim(), currency }); }}>{mutation.isPending ? 'Creating…' : 'File this group'}</PrimaryButton></View></Screen>; }
function Field({ label, theme, ...props }: { label: string; theme: ReturnType<typeof useAppTheme> } & React.ComponentProps<typeof TextInput>) { return <View style={styles.field}><Text style={[typography.label, { color: theme.colors.inkMuted, marginBottom: 7 }]}>{label}</Text><TextInput {...props} placeholderTextColor={theme.colors.inkMuted} style={[styles.input, { backgroundColor: theme.colors.paper, borderColor: theme.colors.line, color: theme.colors.ink }]} /></View>; }
const styles = StyleSheet.create({ container: { paddingTop: 18 }, field: { marginBottom: 17 }, input: { borderRadius: 11, borderWidth: 1, fontSize: 16, minHeight: 52, paddingHorizontal: 14, paddingVertical: 12 }, action: { marginTop: 24 } });
