import { useEffect, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, TextInput, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { GroupStackParamList } from '../navigation/types';
import { getGroup, updateGroup } from '../features/groups/api';
import { PageTitle, PrimaryButton, Screen, SectionLabel } from '../ui/Primitives';
import { useAppTheme, typography } from '../ui/theme';

type Props = NativeStackScreenProps<GroupStackParamList, 'EditGroup'>;
export function EditGroupScreen({ route, navigation }: Props) { const theme = useAppTheme(); const client = useQueryClient(); const group = useQuery({ queryKey: ['groups', route.params.groupId], queryFn: () => getGroup(route.params.groupId) }); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [currency, setCurrency] = useState(''); const [error, setError] = useState(''); useEffect(() => { if (group.data) { setName(group.data.name); setDescription(group.data.description ?? ''); setCurrency(group.data.currency); } }, [group.data]); const mutation = useMutation({ mutationFn: () => updateGroup(route.params.groupId, { name: name.trim(), description: description.trim(), currency }), onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ['groups'] }), client.invalidateQueries({ queryKey: ['groups', route.params.groupId] })]); navigation.goBack(); }, onError: (err) => setError(err.message) }); if (group.isLoading) return <Screen><ActivityIndicator color={theme.colors.primary} /></Screen>; return <Screen scroll contentStyle={styles.container}><PageTitle subtitle="Keep the record recognizable to everyone.">Edit group</PageTitle><SectionLabel>GROUP IDENTITY</SectionLabel><Field label="Group name" value={name} onChangeText={setName} theme={theme} /><Field label="Description" value={description} onChangeText={setDescription} theme={theme} /><Field label="Default currency" value={currency} onChangeText={(value) => setCurrency(value.toUpperCase())} maxLength={3} autoCapitalize="characters" theme={theme} />{!!error && <Text style={[typography.body, { color: theme.colors.error, marginTop: 4 }]}>{error}</Text>}<View style={styles.action}><PrimaryButton disabled={mutation.isPending} onPress={() => { if (!name.trim() || !/^[A-Z]{3}$/.test(currency)) return setError('Enter a valid name and 3-letter currency.'); mutation.mutate(); }}>{mutation.isPending ? 'Saving…' : 'Save changes'}</PrimaryButton></View></Screen>; }
function Field({ label, theme, ...props }: { label: string; theme: ReturnType<typeof useAppTheme> } & React.ComponentProps<typeof TextInput>) { return <View style={styles.field}><Text style={[typography.label, { color: theme.colors.inkMuted, marginBottom: 7 }]}>{label}</Text><TextInput {...props} placeholderTextColor={theme.colors.inkMuted} style={[styles.input, { backgroundColor: theme.colors.paper, borderColor: theme.colors.line, color: theme.colors.ink }]} /></View>; }
const styles = StyleSheet.create({ container: { paddingTop: 18 }, field: { marginBottom: 17 }, input: { borderRadius: 11, borderWidth: 1, fontSize: 16, minHeight: 52, paddingHorizontal: 14, paddingVertical: 12 }, action: { marginTop: 24 } });
