import { useQuery } from '@tanstack/react-query';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { GroupStackParamList } from '../navigation/types';
import { listGroups, type Group } from '../features/groups/api';
import { OutlineButton, PageTitle, Paper, PrimaryButton, Screen, SectionLabel } from '../ui/Primitives';
import { useAppTheme, typography } from '../ui/theme';

type Props = NativeStackScreenProps<GroupStackParamList, 'GroupList'>;
export function GroupsScreen({ navigation }: Props) {
  const theme = useAppTheme(); const groups = useQuery({ queryKey: ['groups'], queryFn: listGroups });
  return <Screen contentStyle={styles.container}><View style={styles.top}><PageTitle subtitle="Your shared spaces, filed together.">Groups</PageTitle><View style={styles.actions}><View style={styles.actionSlot}><OutlineButton onPress={() => navigation.navigate('JoinGroup')}>Join with code</OutlineButton></View><View style={styles.actionSlot}><PrimaryButton onPress={() => navigation.navigate('CreateGroup')}>Create group</PrimaryButton></View></View></View>{groups.isLoading ? <ActivityIndicator color={theme.colors.primary} /> : groups.isError ? <Paper><Text style={[typography.body, { color: theme.colors.error }]}>Unable to load groups. Check your connection and retry.</Text></Paper> : <FlatList data={groups.data ?? []} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} refreshing={groups.isRefetching} onRefresh={() => void groups.refetch()} ListHeaderComponent={<SectionLabel>{groups.data?.length ? `${groups.data.length} ACTIVE RECORDS` : 'NO RECORDS YET'}</SectionLabel>} ListHeaderComponentStyle={styles.listHeader} ListEmptyComponent={<Paper style={styles.empty}><Text style={[typography.headline, { color: theme.colors.ink }]}>Start a shared record.</Text><Text style={[typography.body, { color: theme.colors.inkMuted, marginTop: 8 }]}>Create a group for a trip, a meal, a home, or anything you pay for together.</Text></Paper>} renderItem={({ item }) => <GroupRow group={item} onPress={() => navigation.navigate('GroupDetail', { groupId: item.id })} />} />}</Screen>;
}
function GroupRow({ group, onPress }: { group: Group; onPress: () => void }) { const theme = useAppTheme(); return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.row, { backgroundColor: theme.colors.paper, borderColor: theme.colors.line }, pressed && { opacity: 0.7 }]}><View style={[styles.index, { backgroundColor: theme.colors.primary }]}><Text style={[styles.indexText, { color: theme.colors.onPrimary }]}>{group.name.slice(0, 1).toUpperCase()}</Text></View><View style={styles.copy}><Text numberOfLines={1} style={[typography.title, { color: theme.colors.ink }]}>{group.name}</Text><Text numberOfLines={1} style={[typography.body, { color: theme.colors.inkMuted, marginTop: 3 }]}>{group.currency}{group.description ? ` · ${group.description}` : ''}</Text></View><Text style={[typography.label, { color: theme.colors.primary, fontSize: 9 }]}>VIEW</Text></Pressable>; }
const styles = StyleSheet.create({ container: { flex: 1, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 16 }, top: { paddingBottom: 8 }, actions: { flexDirection: 'row', gap: 10 }, actionSlot: { flex: 1 }, list: { paddingBottom: 30 }, listHeader: { paddingTop: 6, paddingBottom: 6 }, row: { alignItems: 'center', borderRadius: 16, borderWidth: 1, flexDirection: 'row', marginBottom: 10, padding: 14 }, index: { alignItems: 'center', borderRadius: 10, height: 44, justifyContent: 'center', width: 44 }, indexText: { fontSize: 18, fontWeight: '900' }, copy: { flex: 1, marginLeft: 12, minWidth: 0, paddingRight: 8 }, empty: { marginTop: 2 } });
