import { useQuery } from '@tanstack/react-query';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useAuth } from '../auth/AuthProvider';
import { listGroups } from '../features/groups/api';
import { Paper, Rule, Screen, SectionLabel, StatusMark } from '../ui/Primitives';
import { useAppTheme, typography } from '../ui/theme';

export function HomeScreen() {
  const theme = useAppTheme(); const { session } = useAuth(); const groups = useQuery({ queryKey: ['groups'], queryFn: listGroups });
  const firstName = session?.user.email?.split('@')[0] ?? 'there';
  return <Screen scroll contentStyle={styles.container}><View style={styles.header}><View><SectionLabel color={theme.colors.primary}>YOUR LEDGER</SectionLabel><Text style={[typography.display, { color: theme.colors.ink }]}>Good to see you,</Text><Text style={[typography.display, { color: theme.colors.primary }]}>{firstName}.</Text></View><View style={[styles.dateStamp, { borderColor: theme.colors.line }]}><Text style={[typography.label, { color: theme.colors.inkMuted, fontSize: 9 }]}>AUG</Text><Text style={[styles.dateNumber, { color: theme.colors.ink }]}>25</Text></View></View><Paper style={[styles.balancePaper, { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary }]}><View style={styles.balanceHeader}><Text style={[typography.label, { color: theme.colors.onPrimary, fontSize: 10 }]}>CURRENT POSITION</Text><StatusMark tone="green">MVP</StatusMark></View><Text style={[styles.balanceTitle, { color: theme.colors.onPrimary }]}>Your shared money, in one place.</Text><Text style={[typography.body, { color: theme.colors.onPrimary, opacity: 0.78, marginTop: 8 }]}>Create a group or join an invite to start your first record.</Text><View style={[styles.balanceRule, { backgroundColor: theme.colors.onPrimary }]} /><View style={styles.balanceFooter}><Text style={[typography.label, { color: theme.colors.onPrimary, fontSize: 9 }]}>NO BALANCE RECORDED</Text><Text style={[typography.label, { color: theme.colors.onPrimary, fontSize: 9 }]}>READY TO FILE</Text></View></Paper><View style={styles.sectionHeader}><Text style={[typography.title, { color: theme.colors.ink }]}>Recent groups</Text><Text style={[typography.label, { color: theme.colors.inkMuted, fontSize: 9 }]}>{groups.data?.length ?? 0} FILED</Text></View>{groups.data?.length ? groups.data.slice(0, 4).map((group) => <Paper key={group.id} style={styles.groupRow}><View style={[styles.groupMark, { backgroundColor: theme.colors.paperMuted }]}><Text style={[styles.groupMarkText, { color: theme.colors.primary }]}>{group.name.slice(0, 1).toUpperCase()}</Text></View><View style={styles.groupCopy}><Text style={[typography.title, { color: theme.colors.ink }]}>{group.name}</Text><Text style={[typography.body, { color: theme.colors.inkMuted, marginTop: 2 }]}>{group.currency}{group.description ? ` · ${group.description}` : ''}</Text></View><Text style={[typography.label, { color: theme.colors.primary, fontSize: 9 }]}>OPEN</Text></Paper>) : <Paper style={styles.empty}><Text style={[typography.title, { color: theme.colors.ink }]}>Your first group is waiting.</Text><Text style={[typography.body, { color: theme.colors.inkMuted, marginTop: 6 }]}>Once a group is filed, its latest activity will appear here.</Text></Paper>}<View style={[styles.note, { borderColor: theme.colors.line }]}><Rule /><Text style={[typography.body, { color: theme.colors.inkMuted, marginTop: 12 }]}>Every split keeps its source: who paid, who joined, and what is still owed.</Text></View></Screen>;
}

const styles = StyleSheet.create({ container: { paddingTop: 18 }, header: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between' }, dateStamp: { alignItems: 'center', borderRadius: 10, borderWidth: 1, minWidth: 54, paddingHorizontal: 10, paddingVertical: 7 }, dateNumber: { fontSize: 22, fontWeight: '900', marginTop: 1 }, balancePaper: { marginTop: 24, padding: 20 }, balanceHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, balanceTitle: { fontSize: 22, fontWeight: '800', letterSpacing: -0.4, lineHeight: 28, marginTop: 24, maxWidth: 280 }, balanceRule: { height: 1, marginTop: 22, opacity: 0.32 }, balanceFooter: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 }, sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, marginTop: 28 }, groupRow: { alignItems: 'center', flexDirection: 'row', marginBottom: 10, padding: 14 }, groupMark: { alignItems: 'center', borderRadius: 10, height: 44, justifyContent: 'center', width: 44 }, groupMarkText: { fontSize: 19, fontWeight: '900' }, groupCopy: { flex: 1, marginLeft: 12 }, empty: { marginBottom: 10 }, note: { borderTopWidth: 1, marginTop: 22, paddingTop: 2 } });
