import { useState } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { GroupStackParamList } from '../navigation/types';
import { joinGroup, previewInvite, type InvitePreview } from '../features/groups/api';
import { PageTitle, Paper, PrimaryButton, Screen, SectionLabel } from '../ui/Primitives';
import { useAppTheme, typography } from '../ui/theme';

type Props = NativeStackScreenProps<GroupStackParamList, 'JoinGroup'>;
export function JoinGroupScreen({ navigation }: Props) { const theme = useAppTheme(); const client = useQueryClient(); const [code, setCode] = useState(''); const [preview, setPreview] = useState<InvitePreview | null>(null); const [error, setError] = useState(''); const previewMutation = useMutation({ mutationFn: previewInvite, onSuccess: (data) => { setPreview(data); if (!data) setError('Invite not found or expired.'); }, onError: (err) => setError(err.message) }); const joinMutation = useMutation({ mutationFn: joinGroup, onSuccess: async (groupId) => { await client.invalidateQueries({ queryKey: ['groups'] }); navigation.replace('GroupDetail', { groupId }); }, onError: (err) => setError(err.message) }); return <Screen scroll contentStyle={styles.container}><PageTitle subtitle="Enter the code shared by the group owner.">Join a group</PageTitle><SectionLabel>INVITE CODE</SectionLabel><TextInput autoCapitalize="characters" maxLength={8} value={code} onChangeText={(value) => { setCode(value.toUpperCase()); setPreview(null); setError(''); }} placeholder="ABCD1234" placeholderTextColor={theme.colors.inkMuted} style={[styles.codeInput, { backgroundColor: theme.colors.paper, borderColor: theme.colors.line, color: theme.colors.ink }]} />{!!error && <Text style={[typography.body, { color: theme.colors.error, marginTop: 14 }]}>{error}</Text>}{preview ? <Paper style={styles.preview}><SectionLabel>INVITE FOUND</SectionLabel><Text style={[typography.headline, { color: theme.colors.ink }]}>{preview.group_name}</Text><Text style={[typography.body, { color: theme.colors.inkMuted, marginTop: 6 }]}>Invite expires {new Date(preview.expires_at).toLocaleDateString()}</Text><View style={styles.action}><PrimaryButton disabled={joinMutation.isPending} onPress={() => joinMutation.mutate(code)}>{joinMutation.isPending ? 'Joining…' : 'Join this group'}</PrimaryButton></View></Paper> : <View style={styles.action}><PrimaryButton disabled={previewMutation.isPending || code.length < 8} onPress={() => { setError(''); previewMutation.mutate(code); }}>{previewMutation.isPending ? 'Checking…' : 'Check invite'}</PrimaryButton></View>}</Screen>; }
const styles = StyleSheet.create({ container: { paddingTop: 18 }, codeInput: { borderRadius: 12, borderWidth: 1, fontSize: 25, fontWeight: '900', letterSpacing: 4, minHeight: 62, padding: 16, textAlign: 'center' }, action: { marginTop: 22 }, preview: { marginTop: 22 } });
