import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '../auth/AuthProvider';
import { supabase } from '../lib/supabase';
import { OutlineButton, PageTitle, Paper, PrimaryButton, Screen, SectionLabel } from '../ui/Primitives';
import { useAppTheme, typography } from '../ui/theme';

export function ProfileScreen() {
  const theme = useAppTheme(); const { session, signOut } = useAuth(); const [fullName, setFullName] = useState(''); const [username, setUsername] = useState(''); const [isLoading, setIsLoading] = useState(true); const [isSaving, setIsSaving] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { if (!session?.user.id) return; supabase.from('profiles').select('full_name, username').eq('id', session.user.id).maybeSingle().then(({ data, error }) => { if (data) { setFullName(data.full_name); setUsername(data.username ?? ''); } if (error) setMessage(error.message); setIsLoading(false); }); }, [session?.user.id]);
  async function save() { if (!session?.user.id || !fullName.trim()) return setMessage('Full name is required.'); setIsSaving(true); setMessage(''); const { error } = await supabase.from('profiles').update({ full_name: fullName.trim(), username: username.trim() || null }).eq('id', session.user.id); setIsSaving(false); setMessage(error ? error.message : 'Profile updated.'); }
  if (isLoading) return <Screen><View style={styles.center}><Text style={[typography.body, { color: theme.colors.inkMuted }]}>Loading profile…</Text></View></Screen>;
  return <Screen scroll contentStyle={styles.container}><PageTitle subtitle="Keep the name your group recognizes.">Your profile</PageTitle><Paper style={styles.identity}><View style={styles.identityTop}><View style={[styles.profileMark, { backgroundColor: theme.colors.primary }]}><Text style={[styles.profileInitial, { color: theme.colors.onPrimary }]}>{(fullName || session?.user.email || 'S').slice(0, 1).toUpperCase()}</Text></View><View style={styles.identityCopy}><Text style={[typography.title, { color: theme.colors.ink }]}>{fullName || 'Unnamed member'}</Text><Text style={[typography.body, { color: theme.colors.inkMuted, marginTop: 3 }]}>{session?.user.email}</Text></View></View><View style={[styles.memberStamp, { borderColor: theme.colors.line }]}><SectionLabel>MEMBERSHIP</SectionLabel><Text style={[typography.body, { color: theme.colors.inkMuted }]}>Your profile appears to other members in groups you share.</Text></View></Paper><Text style={[typography.label, { color: theme.colors.inkMuted, marginBottom: 8, marginTop: 26 }]}>IDENTITY CARD</Text><TextInput value={fullName} onChangeText={setFullName} placeholder="Full name" placeholderTextColor={theme.colors.inkMuted} style={[styles.input, { backgroundColor: theme.colors.paper, borderColor: theme.colors.line, color: theme.colors.ink }]} /><TextInput autoCapitalize="none" value={username} onChangeText={setUsername} placeholder="Username (optional)" placeholderTextColor={theme.colors.inkMuted} style={[styles.input, { backgroundColor: theme.colors.paper, borderColor: theme.colors.line, color: theme.colors.ink }]} /><Text style={[typography.body, { color: theme.colors.inkMuted, marginTop: 4 }]}>Use a short name your friends can find.</Text>{!!message && <Text style={[typography.body, { color: message === 'Profile updated.' ? theme.colors.success : theme.colors.error, marginTop: 16 }]}>{message}</Text>}<View style={styles.buttons}><PrimaryButton onPress={save} disabled={isSaving}>{isSaving ? 'Saving…' : 'Save profile'}</PrimaryButton><OutlineButton onPress={signOut} destructive>Log out</OutlineButton></View></Screen>;
}
const styles = StyleSheet.create({ container: { paddingTop: 18 }, center: { alignItems: 'center', flex: 1, justifyContent: 'center' }, identity: { padding: 16 }, identityTop: { alignItems: 'center', flexDirection: 'row' }, profileMark: { alignItems: 'center', borderRadius: 30, height: 60, justifyContent: 'center', width: 60 }, profileInitial: { fontSize: 25, fontWeight: '900' }, identityCopy: { flex: 1, marginLeft: 14 }, memberStamp: { borderTopWidth: 1, marginTop: 16, paddingTop: 14 }, input: { borderRadius: 11, borderWidth: 1, fontSize: 16, marginBottom: 10, minHeight: 52, paddingHorizontal: 14 }, buttons: { gap: 10, marginTop: 26 } });
